spring.application.name=backend
spring.output.ansi.enabled=ALWAYS

openai.api.key=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
spring.datasource.url=jdbc:mysql://database-1.c580mikw8lqh.ap-northeast-2.rds.amazonaws.com:3306/aws_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=hongik1
spring.datasource.password=hongik1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

